name: Hello World Facile
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-facile-codecommit-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World"
